name: Run linters

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.12

      - name: Check code style
        run: uv run ruff check src docs tests

      - name: Check formatting
        run: uv run ruff format --check src docs tests

      - name: Check type annotations
        run: uv run ty check src docs # TODO: add tests
