name: Tutorials

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
  release:
    types:
      - published

jobs:
  notebooks:
    name: "Build the notebooks for the docs"
    runs-on: ubuntu-latest
    if:
      ${{ github.event_name == 'push' ||
      github.event_name == 'release' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'tutorials')) }}
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --group docs

      - name: Execute the notebooks
        # TODO: docs/tutorials/astrometry/*.ipynb
        run: |
            for nb in docs/tutorials/rv/*.ipynb; do
            echo "Executing $nb"
            uv run jupyter nbconvert --to notebook --execute --inplace "$nb"
            done

      - uses: actions/upload-artifact@v7
        with:
            name: notebooks-for-${{ github.sha }}
            path: docs/tutorials

      - name: Trigger RTDs build
        if: ${{ github.event_name != 'pull_request' }}
        uses: dfm/rtds-action@v1.1.0
        with:
            webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
            webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
            commit_ref: ${{ github.ref }}
